blank_issues_enabled: false
contact_links:
  - name: MeSmile Discord discussion
    url: https://discord.gg/mesmile-oss
    about: Please ask and answer questions here.
  - name: Report a security vulnerability
    url: https://github.com/aaif-MeSmile/MeSmile/security/policy
    about: Please report security vulnerabilities here.
